name: Secret Scanning

on:
  push:
    branches:
      -main
    pull_request:
      types: [closed]
      branched:
        -main

jobs:
  secret_scan:
    runs-on: [label-1]
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Run Trufflehog to scan for secrets 
      run: |
        REPO_NAME=$(basename $(git rev-parse --show-toplevel))
        OUTPUT_FILE="${REPO_NAME}.json"
